### ISSUE TITLE
Add support for bilingual, custom image and color in button 

### ISSUE THREAD

**Issue by igobranco** [arquivo/RedirectApp#1]
New configuration options - columns in
https://docs.google.com/spreadsheets/d/1e4mmEdcIFR5kuFUGa1X2NaaK3qy0nu06m3oD3zDjp7w/edit#gid=0

- Default Language (pt/en)
- Message PT (current Message option)
- Message EN
- Link PT
- Link EN
- Image (it should be relative to arquivo.pt, it could be hosted directly by redirect app or it could be wayback image)
- Different button color code

**Comment by igobranco** [comment]
Remove bootstrap.

Add this styles to container css class:
```css
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #333;
}

a {
    color: #428bca;
    text-decoration: none;
}
```


Add a div before button, like this:
```html
<div class=center-text>
  <a> ... </a>
</div>
```

On custom.css change style from padding-bottom to padding-top.

For custom button color code, if defined, add a style atributo to the anchor  (button) with a different background-color. Other color like for box-shadow and text-shadow use CSS3 color hsl to make it relative or use brightness() css function.
